### ISSUE TITLE
Game crashes when immersive portals is installed (1.20.4)

### ISSUE THREAD

**Issue by yuckdevchan** [enjarai/mini-tardis#23]
The game crashes when I try and attract a TARDIS (at the moment I'm supposed to be teleported into the TARDIS).

This only happens when Immersive Portals mod is installed.

mini tardis: BOTI mod is not installed, only immersive portals.

Game crashes with following error thrown by immersive portals:

```
java.lang.RuntimeException: Missing Dimension mini_tardis:tardis/4efddff4-ce9a-4c99-b2af-6576b7b9e00b
	at qouteall.q_misc_util.dimension.DimensionIdRecord.getIntId(DimensionIdRecord.java:50) ~[q_misc_util-3.3.9-d99562ab8310cac6.jar:?]
	at qouteall.q_misc_util.dimension.DimId.writeWorldId(DimId.java:25) ~[q_misc_util-3.3.9-d99562ab8310cac6.jar:?]
	at qouteall.imm_ptl.core.network.IPNetworking.createStcDimensionConfirm(IPNetworking.java:69) ~[imm_ptl_core-3.3.9-1d0ee74905d18634.jar:?]
	at qouteall.imm_ptl.core.teleportation.ServerTeleportationManager.sendPositionConfirmMessage(ServerTeleportationManager.java:407) ~[imm_ptl_core-3.3.9-1d0ee74905d18634.jar:?]
	at qouteall.imm_ptl.core.teleportation.ServerTeleportationManager.updateForPlayer(ServerTeleportationManager.java:441) ~[imm_ptl_core-3.3.9-1d0ee74905d18634.jar:?]
	at qouteall.imm_ptl.core.teleportation.ServerTeleportationManager.tick(ServerTeleportationManager.java:80) ~[imm_ptl_core-3.3.9-1d0ee74905d18634.jar:?]
	at qouteall.q_misc_util.my_util.Signal.lambda$connectWithWeakRef$1(Signal.java:35) ~[q_misc_util-3.3.9-d99562ab8310cac6.jar:?]
	at qouteall.q_misc_util.my_util.Signal.lambda$emit$0(Signal.java:18) ~[q_misc_util-3.3.9-d99562ab8310cac6.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at qouteall.q_misc_util.my_util.Signal.emit(Signal.java:18) ~[q_misc_util-3.3.9-d99562ab8310cac6.jar:?]
	at net.minecraft.server.MinecraftServer.handler$big000$imm_ptl_core$onServerTick(MinecraftServer.java:6828) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:920) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by enjarai** [comment]
This is a known issue, the BOTI addon serves an additional purpose as a compatibility patch with Immersive Portals. It is required if you want to use these mods together.
